[program:laravel-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /home/redalerts/httpdocs/artisan queue:work --tries=3
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/laravel-queue.log
